-- =============================================
-- 巡检人员管理模块 - 数据库脚本
-- 执行日期: 2026-06-13
-- =============================================

-- ---------------------------------------------
-- 1. 创建巡检人员表
-- ---------------------------------------------
CREATE TABLE IF NOT EXISTS inspectors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    phone VARCHAR(20) DEFAULT '',
    responsible_zone VARCHAR(255) DEFAULT '',
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------
-- 2. 为巡检记录表添加 inspector_id 字段，允许为空以兼容历史记录
-- ---------------------------------------------
ALTER TABLE inspections ADD COLUMN IF NOT EXISTS inspector_id BIGINT;

-- ---------------------------------------------
-- 示例数据（可选）
-- ---------------------------------------------
INSERT INTO inspectors (name, phone, responsible_zone, enabled) VALUES
('张三', '13800138001', 'A区-古代文物展区', TRUE),
('李四', '13800138002', 'B区-近现代史展区', TRUE),
('王五', '13800138003', 'C区-民俗文化展区', TRUE),
('赵六', '13800138004', 'A区-古代文物展区', FALSE),
('钱七', '13800138005', 'D区-科技互动展区', TRUE);
